/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.gumbomillennium.plazacam;

import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  void appClassConfiguresConfig() {
    // noop
  }
}
