/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.gumbomillennium.plazacam;

import nl.gumbomillennium.plazacam.config.Config;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  @Test void appClassConfiguresConfig() {
    boolean shouldRun = false;
    if (shouldRun) {

        App appUnderTest = new App();

        appUnderTest.loadConfig();

        var config = appUnderTest.getConfig();

        // Just ensure it works
        assertInstanceOf(Config.class, config);
      }
    }
}
